version: '3'
services:
  nginx-pwa:
    build: ./docker-image
    image: 'alpheios-nginx-ssl:v1'
    container_name: pwa-prototype-container
    ports:
      - '${PWA_HTTP_PORT-8020}:80'
      - "${PWA_HTTPS_PORT-8120}:443"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker-nginx-config/conf.d:/etc/nginx/conf.d
      - ./docker-nginx-config/certs:/etc/nginx/ssl